### ISSUE TITLE
Running on Linux

### ISSUE THREAD

**Issue by vertonghenb** [arichika/RotativaCore#9]
Since it's far cheaper to run on Linux, it might be beneficial to start looking to make this package run on Linux devices.

@arichika Any thoughts?

**Comment by arichika** [comment]
The Windows has a great philosophy for compatibility. In terms of development productivity, I think that the Windows ecosystem remains low cost.

By the way, I think linux support is not difficult. 

Just fix it like this,
https://github.com/arichika/RotativaCore/blob/366f9165412d0318a22c22d531afb22913734c9e/src/RotativaCore/WkhtmltopdfDriver.cs#L8

If wkhtmltopdf works correctly, it will ... work.  work? I think it works with minor modifications.

The most difficult part is to make sure that the latest wkhtmltopdf works correctly in various linux environments.

**Comment by vertonghenb** [comment]
mmm gonna give a spin later this week, I was looking at the exact same line.
Well if you deploy to an Azure App Service the (basic tier) the costs of linux is divided by 7, thats why :)

**Comment by vertonghenb** [comment]
@arichika good news, just tried your fork in a Azure Linux Self contained deployed and it works for the view with model, the others fail, don't know why yet but I think it has to do with the new routing system. The example Linux deploy can be found [here](https://linuxsample.azurewebsites.net/).

Will you merge it into master and create a new deployment ?

**Comment by arichika** [comment]
@vertonghenb thank you so much for good works.
I am using Docker for Windows and checking the operation with the latest wlhtmltopdf.
Please wait a little more. thank you.

**Comment by vertonghenb** [comment]
@arichika ok sure, let me know if you need anything.

**Comment by arichika** [comment]
I clarified some problems and solutions.

### One, Generating url for internal action methods with port num.
For example, In the time that `ActionAsPdf` method calls self hosted action method using `IUrlHelper.Action()`,  library will generated for internal refalencing url with additional ports number.

In the container like docker, the port number is explicitly disclosed, There is a problem here.

The program `IUrlHelper.Action()` generates a URL on port SomeDebugginPortNumber or SomeIntrnalPortNumer in container, but at that number, the container is not waiting for an external connection.

Since the started WkhtmlToPdf process is started by a process different from Container, it must be accessed with the published port number. 

But unfortunately, the program doesn't know which port number will be started and which port number will be `EXPOSE`.

In short, we will need the following improvements:

Information about the host to connect to must be given as an external configuration value under the general Linux Container environment, even if it is your own action method.

### Two, The Problems arounds WkHtmlToPdf Binaries
The latest WkHtmlToPdf has separate installation packages for each Linux distribution. It seems that the prerequisite packages required to work vary depending on the environment. I think that it is difficult to ensure proper operation between the test environment (eg Docker for Windows) and the execution environment (eg AzureWebApps for Linux) simply by placing the Wk binary in the project.

Also, since the procedure for installing dependent programs with Dockerfile is a common method, the WlHtmlToPdf binary should not be included in the Web project, and should be controlled by the execution environment administrator.

### Solutions / Tasks
- The installation of WkHtmlToPdf is specified in Dockerfile.
- The host name and port number of the connection destination should be given from the outside. The default value guarantees the current operation for Windows.


Please wait a little while longer.

**Comment by vertonghenb** [comment]
Using your altest fork it's I got it working in a self contained deployment on Linux.
However deploying it in a docker container on Linux, we have permission issues:
```log
2019-09-10T14:37:34.329544958Z [16:37:34 ERR] Connection id "0HLPLV7O0CT59", Request id "0HLPLV7O0CT59:00000001": An unhandled exception was thrown by the application.
2019-09-10T14:37:34.329620359Z System.ComponentModel.Win32Exception (13): Permission denied
2019-09-10T14:37:34.332483875Z    at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
2019-09-10T14:37:34.332525276Z    at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
2019-09-10T14:37:34.332540376Z    at System.Diagnostics.Process.Start()
2019-09-10T14:37:34.333997184Z    at RotativaCore.WkhtmlDriver.Convert(String wkhtmlPath, String switches, String html, String wkhtmlExe) in /src/source/RotativaCore/WkhtmlDriver.cs:line 50
2019-09-10T14:37:34.334020784Z    at RotativaCore.WkhtmltopdfDriver.ConvertHtml(String wkhtmltopdfPath, String switches, String html) in /src/source/RotativaCore/WkhtmltopdfDriver.cs:line 19
2019-09-10T14:37:34.335053690Z    at RotativaCore.ViewAsPdf.CallTheDriver(ActionContext context) in /src/source/RotativaCore/ViewAsPdf.cs:line 81
2019-09-10T14:37:34.335081791Z    at RotativaCore.AsResultBase.BuildFile(ActionContext context) in /src/source/RotativaCore/AsResultBase.cs:line 231
2019-09-10T14:37:34.335435193Z    at RotativaCore.AsResultBase.ExecuteResult(ActionContext context) in /src/source/RotativaCore/AsResultBase.cs:line 245
2019-09-10T14:37:34.335480093Z    at Microsoft.AspNetCore.Mvc.ActionResult.ExecuteResultAsync(ActionContext context)
2019-09-10T14:37:34.335493093Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2019-09-10T14:37:34.335504093Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
2019-09-10T14:37:34.335514193Z --- End of stack trace from previous location where exception was thrown ---
2019-09-10T14:37:34.335538593Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
2019-09-10T14:37:34.335548593Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
2019-09-10T14:37:34.335558993Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
2019-09-10T14:37:34.335568393Z --- End of stack trace from previous location where exception was thrown ---
2019-09-10T14:37:34.339543317Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2019-09-10T14:37:34.339568717Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
2019-09-10T14:37:34.344599746Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
2019-09-10T14:37:34.344659747Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
2019-09-10T14:37:34.344680447Z    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
2019-09-10T14:37:34.344855448Z    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
2019-09-10T14:37:34.344877848Z    at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```
